[build]
command = "yarn build"
publish = "build"

[[redirects]]
from = "/en/*"
to = "/:splat"

[[redirects]]
from = "/docs/api/rust/*"
to = "https://docs.rs/tauri/1.0.0-rc.0/tauri/"

[[redirects]]
from = "/partners"
to = "/#sponsors"
